"""empty message

Revision ID: c49a2f10d15f
Revises: 35f6f03ca72e
Create Date: 2024-11-16 02:33:26.539258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49a2f10d15f'
down_revision = '35f6f03ca72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('results_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('results_published')
        batch_op.drop_column('time')

    with op.batch_alter_table('exam_registrations', schema=None) as batch_op:
        batch_op.drop_column('attempted')

    # ### end Alembic commands ###
